### ISSUE TITLE
Dispatch changes its reference on every render

### ISSUE THREAD

**Issue by tomaszNowakKivy** [PedroBern/react-hook-use-cancelable-thunk-reducer#1]
"Dispatch" changes its reference on every render, it should probably be memoized, because I cannot pass it to the dependency array of the useEffect.

**Comment by PedroBern** [comment]
Hi @tomaszNowakKivy thanks for opening the issue, but we can't fix this because the dispatch is defined as:

```js
const dispatchThunk = action => (isFunction(action)
    ? action(dispatch, getState)
    : dispatch(action));
```
You can see it [here](https://github.com/PedroBern/react-hook-use-cancelable-thunk-reducer/blob/master/src/index.js#L53).

So if we memoize the dispatch, then it will have the `getState` as dependency, implying in the need of memoizing the `state`, which will be useless, since it is supposed to change often.

I'm closing it, but please let me know if you have further questions or suggestions, maybe we can make it better.
